/* POST */
export const POST_INSERT = "POST_INSERT";
export const POST_INSERT_SUCCESS = "POST_INSERT_SUCCESS";
export const POST_INSERT_FAILURE = "POST_INSERT_FAILURE";
export const POST_LIST = "POST_LIST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILURE = "POST_LIST_FAILURE";

/* CATEGORY */
export const CATEGORY_INSERT = "CATEGORY_INSERT";
export const CATEGORY_INSERT_SUCCESS = "CATEGORY_INSERT_SUCCESS";
export const CATEGORY_INSERT_FAILURE = "CATEGORY_INSERT_FAILURE";
export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILURE = "CATEGORY_LIST_FAILURE";