/* POST */
export const POST_INSERT = "POST_INSERT";
export const POST_INSERT_SUCCESS = "POST_INSERT_SUCCESS";
export const POST_INSERT_FAILURE = "POST_INSERT_FAILURE";
export const POST_LIST = "POST_LIST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILURE = "POST_LIST_FAILURE";

<<<<<<< HEAD
/* DETAIL */
export const DETAIL_INSERT = "DETAIL_INSERT";
export const DETAIL_INSERT_SUCCESS = "DETAIL_INSERT_SUCCESS";
export const DETAIL_INSERT_FAILURE = "DETAIL_INSERT_FAILURE";
export const DETAIL_LIST = "DETAIL_LIST";
export const DETAIL_LIST_SUCCESS = "DETAIL_LIST_SUCCESS";
export const DETAIL_LIST_FAILURE = "DETAIL_LIST_FAILURE";
=======
/* REPLY */
export const REPLY_INSERT = "REPLY_INSERT";
export const REPLY_INSERT_SUCCESS = "REPLY_INSERT_SUCCESS";
export const REPLY_INSERT_FAILURE = "REPLY_INSERT_FAILURE";
export const REPLY_LIST = "REPLY_LIST";
export const REPLY_LIST_SUCCESS = "REPLY_LIST_SUCCESS";
export const REPLY_LIST_FAILURE = "REPLY_LIST_FAILURE";
export const REPLY_DELETE = "REPLY_DELETE";
export const REPLY_DELETE_SUCCESS = "REPLY_DELETE_SUCCESS";
export const REPLY_DELETE_FAILURE = "REPLY_DELETE_FAILURE";
export const REPLY_UPDATE = "REPLY_UPDATE";
export const REPLY_UPDATE_SUCCESS = "REPLY_UPDATE_SUCCESS";
export const REPLY_UPDATE_FAILURE = "REPLY_UPDATE_FAILURE";

/* CATEGORY */
export const CATEGORY_INSERT = "CATEGORY_INSERT";
export const CATEGORY_INSERT_SUCCESS = "CATEGORY_INSERT_SUCCESS";
export const CATEGORY_INSERT_FAILURE = "CATEGORY_INSERT_FAILURE";
export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILURE = "CATEGORY_LIST_FAILURE";

>>>>>>> refs/remotes/origin/4h-project
