/* POST */
export const POST_INSERT = "POST_INSERT";
export const POST_INSERT_SUCCESS = "POST_INSERT_SUCCESS";
export const POST_INSERT_FAILURE = "POST_INSERT_FAILURE";
export const POST_LIST = "POST_LIST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILURE = "POST_LIST_FAILURE";

/* REPLY */
export const REPLY_INSERT = "REPLY_INSERT";
export const REPLY_INSERT_SUCCESS = "REPLY_INSERT_SUCCESS";
export const REPLY_INSERT_FAILURE = "REPLY_INSERT_FAILURE";
export const REPLY_LIST = "REPLY_LIST";
export const REPLY_LIST_SUCCESS = "REPLY_LIST_SUCCESS";
export const REPLY_LIST_FAILURE = "REPLY_LIST_FAILURE";